Problem 1 — NumPy Warm-up
Open a new notebook (Colab or VS Code). Without copy-pasting the examples above:

Create an array of numbers 1–20
Select only even numbers using slicing or filtering
Compute the mean and standard deviation
Create a 4×4 matrix of zeros, then set the diagonal values to 1

In [ ]:
import numpy as np 
#1 
arr1 = [1, 2, 3, 4, 5]
arr2 = []
for i in range(5):
    arr2.append(i+1)
print(arr1)
print(arr2)
arr3 = np.arange(1, 6)
print(arr3)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [ ]:
#2 
#slicing
arr4 = []
for i in range(len(arr1)):
    if i%2 == 0:
        arr4.append(arr1[i])
print(arr4)

arr1[::2]
arr1[1::2]

#filtering
arr5 = []
for i in arr1:
    if i%2 == 0:
        arr5.append(i)
print(arr5)

arr6 = [i for i in arr1 if i%2 == 0]
print(arr6)


[1, 3, 5]
[2, 4]
[2, 4]


In [14]:
#3 
mean = sum(arr1)/len(arr1)
print(mean)

print(arr3.mean())

standard_deviation = (sum([(i-mean)**2 for i in arr1])/len(arr1))**0.5
print(standard_deviation)

print(arr3.std())


3.0
3.0
1.4142135623730951
1.4142135623730951


In [23]:
#4 
'''
[0 0]
[0 0]
'''
arr7 = np.zeros((2, 2))
for i in range(arr7.shape[0]):
    for j in range(arr7.shape[1]):
        if i == j:
            arr7[i][j] = 1
print(arr7)

def identity_matrix(n):
    arr = np.zeros((n, n))
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            if i == j:
                arr[i][j] = 1
    print(arr)
identity_matrix(2)
identity_matrix(4)
identity_matrix(8)


[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
