Problem 1 — NumPy Warm-up
Open a new notebook (Colab or VS Code). Without copy-pasting the examples above:

Create an array of numbers 1–20
Select only even numbers using slicing or filtering
Compute the mean and standard deviation
Create a 4×4 matrix of zeros, then set the diagonal values to 1

In [1]:
import numpy as np

arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [2]:
even_values = arr[arr % 2 == 0]
even_values

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [3]:
evens = arr[::2][1:] if arr[0] % 2 != 0 else arr[::2]
evens

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [4]:
even_index_elements = np.where(arr % 2 == 0, arr, 0)
even_index_elements = even_index_elements[even_index_elements != 0]
even_index_elements

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
mean_val = np.mean(arr)
std_val = np.std(arr)
mean_val, std_val

(10.5, 5.766281297335398)

In [6]:
matrix = np.zeros((4, 4))
np.fill_diagonal(matrix, 1)
matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])